---
# This playbook has been tested on CentOS 9 Stream
#
- name: A playbook to install and start chrony
  hosts: webservers
  
  tasks:
    - name: stop chronyd service
      service:
        name: chronyd
        state: stopped
        enabled: no

    - name: uninstall chrony
      yum:
        name: chrony
        state: absent

...
