---
# tasks file for chrony

- name: install chrony  # name of the task
  yum:   # module name
    name: chrony  #parameter:value
    state: installed #parameter:value

- name: start chrony
  service:
    name: chronyd
    state: started
    enabled: yes

- name: reconfigure the new chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    backup: yes
  notify:
    - restart chrony

...
